version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  lost-curve.cyrhades.fr:
    image: anssi/fcsc2021-crypto-lost-curve:latest
    ports:
      - ${PORT_SSH}:4000
